name: resnet_gammanet
import_prepath: models.base_gammanet
import_class: BaseResNetGN
args:
  base_ff: -model.resnet
  gn_params: [['layer1', 3],['layer2', 1],['layer3', 1],['layer4', 1],['layer3', 1],['layer2', 1],['layer1', 1]]
  timesteps: 8
  hidden_init: 'identity'
  attention: 'gala' # 'se', None
  attention_layers: 1 #2
  saliency_filter_size: 3 #5
  norm_attention: False
  normalization_fgru: InstanceNorm2d
  normalization_fgru_params: {'affine': True}
  normalization_gate: InstanceNorm2d
  normalization_gate_params: {'affine': True}
  force_alpha_divisive: False
  force_non_negativity: True
  multiplicative_excitation: True
  ff_non_linearity: 'ReLU'
  us_resize_before_block: True
  readout: True
  readout_feats: 1