name: BSDS500_crops
import_prepath: data.BSDS500_100
import_class: BSDS500
images_path: /media/data_cifs/pytorch_projects/datasets/BSDS500_crops/data/images/test
labels_path: /media/data_cifs/pytorch_projects/datasets/BSDS500_crops/data/groundTruth/test
transform: 
  Resize:
    size: 320
input: image
target: label
