type: test
name: bd_test
import_prepath: experiments.contour_detection
import_class: BDTest
testset: -dataset.BSDS500_test
dataloader:
  name: pt_loader
  kwargs: 
    batch_size: 1
    shuffle: false 
    num_workers: 4
    pin_memory: True
cuda: true
loss: class_balanced_bce_with_logits
eval: pixel_error
dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${name}
plot_recurrence: true
exp_cfg: outputs/2020-01-12/15-05-50_bd_train_base_gammanet/config.yaml
checkpoint: outputs/2020-01-12/15-05-50_bd_train_base_gammanet/275.pth.tar